litmuschaos/litmus-e2e

.gitlab-ci.yml, Makefile, README.md, build/gitlab/stages/1-cluster-setup/gcp, build/gitlab/stages/2-cluster-cleanup/cluster-cleanup, experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/node-cpu-hog.yml, nginx/deployment/app_deploy.yml, nginx/deployment/nginx.j2, nginx/liveness/liveness-app.j2, nginx/liveness/liveness.yml, utils/chaosengine.j2, utils/status_app_pod.yml
- This PR contains the Gitlab e2e pipeline with BDD and other test cases for Generic experiments of litmus.
The Different Stages of the pipeline are:
- Setup
- Install
- Deploy
- Generic-experiment
- Infra-experiment
- App-cleanup
- Cleanup
[View Pipeline](https://gitlab.com/uditgaurav1/litmus-2e2-testing/pipelines/108063168)
=> (feat): Add Gitlab e2e pipeline with test cases for Generic Charts

baseline/baseline, baseline/commit-writer.yml
- Add baseline file to record all the commit from different litmus repository.
=> (feat): Add baseline file to record all the commit from different litmus repository

utils/chaosengine.j2
- Modify chaos engine spec 
- Add env and changing the indentation accordingly
=> (refactor): Modify ChaosEngine Spec

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/node-cpu-hog.yml
- Fixing the URL of node cpu hog experiment
=> (Fix): Fixing the URL of node cpu hog experiment

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/node-cpu-hog.yml
- Rename experiment cpu-hog to node-cpu-hog
=> (refactor): Rename experiment cpu-hog to node-cpu-hog

.gitlab-ci.yml
- Add similar tags for a specific runner
=> (feat): Add similar tags for a specific runner

.gitlab-ci.yml, utils/chaosengine.j2
-  Adding command tag and fixing chaosengine
=> (fix): Adding command tag and fixing chaosengine

README.md
- Adding different OpenEBS Experiments test cases in README.md
=> (feat): Adding different OpenEBS Experiments test cases in README.md

tests/openebs-pool-pod-failure_test.go
issue - https://github.com/litmuschaos/litmus/issues/1197
**_This PR contains:-_**
- The addition of validations (Test cases) for the openebs pool pod failure experiment
**_The test cases which are added:_**
- _**Verdict Check**_
- It involves a basis verdict check of the experiment. It is already done at the end of the experiment.
- _**Resource Version test**_
- In the resource version test, it has been tested whether the resource version of the CSP pod has been changed after chaos injection. For successful chaos injection - the value of Resource Version should change.
- **_Pod Name test_**
- In openebs pool pod failure experiment, anyone replica of the csp pod is getting down and new replicas come up with a new pod name this change in …
=> (feat): Adding Validations (Test cases) for openebs pool pod failure experiment

Makefile, utils/chaosengine.j2
- Changing image tag of operator to latest
=> (refactor): Changing image tag of operator to latest

tests/install-litmus_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, vendor/github.com/litmuschaos/chaos-operator/tests/bdd/bdd_test.go
- Changing the operator image tag to the latest
=> Changing the operator image tag to the latest

Makefile, experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml, utils/chaosengine.j2, utils/rbac.yaml
- Provided all permissions for experiments's serviceAcccount for now. We can change the permission in future (per exp sa)
=> (refactor): Adding separate sa for all generic experiments

tests/install-litmus_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, utils/rbac.yaml
- Provided all permissions for experiments's serviceAcccount for now. We can change the permission in future (per exp sa)
=> (refactor): Adding separate sa for all openebs experiments

build/gitlab/stages/1-gke-setup/cluster-setup, build/gitlab/stages/2-gke-cleanup/cluster-cleanup
- Modify Cluster Setup script by adding branch
=> (refactor): Modify Cluster Setup script by adding branch

build/gitlab/stages/1-gke-setup/cluster-setup, build/gitlab/stages/2-gke-cleanup/cluster-cleanup
- Modify Cluster Setup script by adding branch name
=> (refactor): Modify Cluster Setup script by adding branch name - for generic branch

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml
- Added experiment specific service Account in generic experiments
=> (feat): Added experiment specific service Account in generic experiments

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml
=> (fix): Added experiment specific rbac

experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml
=> (fix): fixing the indentation for infra exp

tests/openebs-pool-container-failure_test.go
- Adding chaos experiment to test file
=> (bug): Adding chaos experiment to test file

tests/install-litmus_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
=> (test): Testing with 1.0.0 image

build/gitlab/stages/1-gke-setup/cluster-setup, build/gitlab/stages/2-gke-cleanup/cluster-cleanup, tests/app-cleanup_test.go, tests/app-deploy_test.go, tests/install-litmus_test.go, tests/litmus-cleanup_test.go, tests/openebs-cleanup_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-setup_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Adding service account per experiment along with BDDs
=> [Update staging]: Adding service account per experiment along with BDDs

tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go
=> (bug fixes): Fixing Bdds issues

.gitlab-ci.yml, Makefile, tests/openebs-control-plane-validation_test.go
Signed-off-by: Raj <raj.das@mayadata.io>
- Adding control plane validation experiment in pipeline
=> (feat): Adding control plane validation experiment in pipeline

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
-  Modify [openebs-staging] branch as ci enabled
=> (refactor): Modify [openebs-staging] branch as ci enabled for experiments

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml, utils/chaosengine.j2
=> (feat) Updating generic experiments to run with ci tag & ramp_time

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Fix in openebs-staging branch as ci enabled
=> Fix in openebs-staging branch as ci enabled

experiments/generic/container-kill.yml, experiments/generic/pod-cpu-hog.yml, experiments/generic/pod-delete.yml, experiments/generic/pod-network-corruption.yml, experiments/generic/pod-network-latency.yml, experiments/generic/pod-network-loss.yml, experiments/infra/disk-fill.yml, experiments/infra/node-cpu-hog.yml, experiments/infra/node-drain.yml
- Updating generic experiments to run with ci tag
=> (feat) Updating generic experiments to run with ci tag

tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Modify BDDs according to the latest changes
=> refactor(BDDs): Modify BDDs according to the latest changes

tests/node-memory-hog_test.go
- Adding node-memory-hog experiment in  generic pipeline
=> Adding node-memory-hog experiment in  generic pipeline

.gitlab-ci.yml, Makefile
=> Add node memory hog job in pipeline

tests/install-litmus_test.go
- Installing Litmus with all components having ci image
=> Installing Litmus with all components having ci image

tests/install-litmus_test.go
- Installing all litmus components with ci image tag
=> Installing all litmus components with ci image tag

tests/install-litmus_test.go
=> installing litmus form chaos operator

tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Getting ci image instead of latest image in all exp…
=> feat(experiment): Getting ci image instead of latest image in all experiments

NOTICE.md
- Adds a license notice
Signed-off-by: ksatchit <ksatchit@mayadata.io>
=> (chore)license: addd license notice

.gitlab-ci.yml, Makefile
- Renaming openebs control plane chaos in Makefile
=> bug-fix(experiment): Renaming openebs control plane chaos in Makefile

tests/install-litmus_test.go, tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
=> Enhancement(image_tags): Taking Image tag from ENV

pkg/utils/watchJob.go
-  Adding some wait time for job creation
=> bug-fix(generic): Adding some wait time for job creation

pkg/utils/watchJob.go, tests/install-litmus_test.go
- Adding some wait time for job creation and fxing install litmus in  openebs-staging branch
=> Adding some wait time for job creation and fxing install litmus in  openebs-staging branch

pkg/utils/watchJob.go, tests/install-litmus_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Adding some wait time for job creation
=> fix(watchJob): Adding some wait time for job creation

pkg/utils/watchJob.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/install-litmus_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Add waiting for job to get created and using image tag from env
=> Bug-Fix(watchJob): Add waiting for job to get created and using image tag from env

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go
- Fix the image tags of some of the experiments
=> Fix the image tags of the experiments

tests/disk-fill_test.go, tests/node-cpu-hog_test.go
- Fix the image tags of the experiments
=> (bug-fix): Fix the image tags of the experiments

tests/install-litmus_test.go
- Typo fix in litmus installation
=> (bug): Typo fix in litmus installation

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Typo fix in openebs experiments
=> (fix): Typo fix in openebs experiments

tests/disk-fill_test.go, tests/install-litmus_test.go
- [generic staging] -> [generic]
=> [generic staging] -> [generic]

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go
- Add pvc in the pool experiments
=> Add pvc in the pool experiments

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
=> openebs-staging - openebs

result_update.py, tests/container-kill_test.go
=> Add result update in gitlab

result_update.py, tests/container-kill_test.go
Result update generic-staging python script call
=> feat(result-update): Result update generic-staging python script call

result_update.py, tests/container-kill_test.go
- Add readme update script for repos
=> Add readme update script for repos

LICENSE
=> [LICENSE]: Add Apache License 2.0 to generic branch

LICENSE
=> [LICENSE]: Add Apache License 2.0 to master branch

LICENSE
=> [LICENSE]: Add Apache License 2.0 to openebs branch

LICENSE
=> [LICENSE]: Add Apache License 2.0 to baseline branch

tests/container-kill_test.go, utils/result_update.py
- Restructuring the directories
=> Restructuring the directories

pkg/utils/watchJob.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, utils/result_update.py
- Adding result update in every job
=> Adding result update in every job

generic-pipeline/README.md, openebs-pipeline/README.md
- Add directories for pipeline updates
=> (feat): Add directories for pipeline updates

pkg/utils/installRbac.go, pkg/utils/statusCheck.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
This PR contains:
1. Remove typo of the app name 
2. Remove comment of openebs form generic experiments
3. Take rbac namespace
4. Take engine status namespace
5. change engine name in the edit engine spec
6. make status check util for runner pod
=> (refactor): Fixing typo and modify functions and utils

pkg/utils/watchJob.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, utils/result_update.py
- Add pipeline updates/history in baseline branch
=> feat(result_updation): Add pipeline updates/history in baseline branch

.gitlab-ci.yml, Makefile, pkg/utils/watchJob.go, tests/admin-mode_test.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, types/types.go
- Add Admin mode check in the pipeline
=> (Test case): Add Admin mode check in the pipeline

tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Syntax error fix for generic experiments
=> (fix): Syntax error fix for generic experiments

tests/install-litmus_test.go, tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, types/types.go
- Support pipeline runs with custom images for openebs experiments
=> Support pipeline runs with custom images for openebs experiments

README.md
- Add steps to view the pipeline job history
=> [update]: Add steps to view the pipeline job history

pkg/utils/watchJob.go, tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, utils/result_update.py
-  Add openebs pipeline result updation table in baseline branch
=> feat(result update): Add openebs pipeline result updation table in baseline branch

tests/admin-mode_test.go
- There are some dependencies between some of the test cases with another test case which is not mandatory also. This is to remove such dependencies. Like in admin-mode functionality we are deleting the pod-delete experiment and again applying it, we can create the experiment with slightly other names and can do this and deleting things can be done in the cleanup stage. What if pod-delete itself doesn't run ? in such case admin mode will also fail, this should not be the case.
issue - https://github.com/litmuschaos/litmus/issues/1410
=> refactor(admin-mode): Remove dependency between test cases

tests/reconcile-resiliency_test.go
- Typo fix in reconcile resiliency check
=> fix(bug): Typo fix in reconcile resiliency check

.gitlab-ci.yml, Makefile, tests/disk-fill_test.go, tests/node-drain_test.go, tests/pod-memory-hog_test.go, types/types.go
- Adding pod memory hog experiment in the pipeline
=> Adding pod memory hog experiment in the pipeline

tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Add chaos engine verdict check for experiment bdds
issue - https://github.com/litmuschaos/litmus/issues/1402
=> feat(bdd): Add chaos engine verdict check for experiment bdds

tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Add chaoengine verdict check for openebs experiment bdds
issue - https://github.com/litmuschaos/litmus/issues/1402
=> feat(bdd): Add chaoengine verdict check for openebs experiment bdds

.gitlab-ci.yml, tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- This Pull Request contains
- Add wait time for chaosengine verdict
- Separating app deploy stage
=> Add wait time for chaosengine verdict and separating app deploy stage

tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, tests/reconcile-resiliency_test.go
- Fix the ChaosHub experiment link
=> (bug): Fix the ChaosHub experiment link

tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Fix the openebs chaoshub experiment link
=> (bug): Fix the openebs chaoshub experiment link

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go
- (bug): fix openebs pool experiment engine name
=> (bug): fix openebs pool experiment engine name

tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
- Fix increasing wait time for chaosengine verdict
=> (bug): Fix increasing wait time for chaosengine verdict

tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Fix adding wait time for chaosengine verdict
=> (bug): Fix adding wait time for chaosengine verdict

.gitlab-ci.yml, Makefile, build/gitlab/stages/3-cluster-connect/cluster-connect, build/gitlab/stages/4-cluster-disconnect/cluster-disconnect
- Shifting pipeline runs to Onprem for generic experiments
=> feat(pipeline): Shifting e2e pipeline execution on Onprem cluster for generic experiments

.gitlab-ci.yml, Makefile, build/gitlab/stages/3-cluster-connect/cluster-connect, build/gitlab/stages/4-cluster-disconnect/cluster-disconnect
This PR is for shifting openebs pipeline runs on onprem cluster.
=> feat(pipeline): Shifting e2e pipeline runs to lab machine for openebs experiments

build/gitlab/stages/4-cluster-disconnect/cluster-disconnect
- Modify cluster disconnect script to remove the dependencies first
=> (refactor): Modify cluster disconnect script to remove the dependencies first

build/gitlab/stages/4-cluster-disconnect/cluster-disconnect
- Modify cluster disconnect script to remove the dependencies first for generic branch
=> (refactor): Modify cluster disconnect script to remove the dependencies first for generic branch

.gitlab-ci.yml, .travis.yml, Dockerfile, Makefile, build/push
- Creating litmus-e2e image and using it to run the tests
=> [Staging]: Creating litmus-e2e image and using it to run the tests

Dockerfile
-  Adding build-essential in Dockerfile
=> [Staging]: Adding build-essential in Dockerfile

.gitlab-ci.yml, .travis.yml, Dockerfile, Makefile, build/push
- This PR binds the different test cases in an image which is now used to run the tests. It reduces the dependencies on the target machine or cluster to perform a certain operations. 
issue - https://github.com/litmuschaos/litmus/issues/1494
=> core(image): Adding using docker image to run the e2e tests

Makefile
- Add mandatory variables in the Makefile
=> core(image): Add mandatory variables in the Makefile

Makefile
- Giving the correct repository details for pushing image
issue - litmuschaos/litmus#1494
=> fix(push): Giving the correct repository details for pushing image

.gitlab-ci.yml, .travis.yml, Dockerfile, Makefile, build/push
- This PR is for bundling litmus e2e litmus tests in an image 
issue - litmuschaos/litmus#1494
=> chore(image): Add docker image to run litmus openebs tests

.gitlab-ci.yml, Makefile, tests/kubelet-service-kill_test.go
**Why do we need this?**
- This PR is for adding another experiment BDD in the e2e pipelines. The experiment added is kubelet service kill experiment which is an addition in our infra experiments.
=> chore(BDDs): Add kubelet service kill experiment in the e2e pipeline

baseline/commit-writer.yml, generic-pipeline/container-kill/README.md, generic-pipeline/disk-fill/README.md, generic-pipeline/kubelet-service-kill/README.md, generic-pipeline/node-cpu-hog/README.md, generic-pipeline/node-drain/README.md, generic-pipeline/node-memory-hog/README.md, generic-pipeline/pod-cpu-hog/README.md, generic-pipeline/pod-delete/README.md, generic-pipeline/pod-memory-hog/README.md, generic-pipeline/pod-network-corruption/README.md, generic-pipeline/pod-network-duplication/README.md, generic-pipeline/pod-network-latency/README.md, generic-pipeline/pod-network-loss/README.md, openebs-pipeline/openebs-control-plane-chaos/README.md, openebs-pipeline/openebs-pool-container-failure/README.md, openebs-pipeline/openebs-pool-pod-failure/README.md, openebs-pipeline/openebs-target-container-failure/README.md, openebs-pipeline/openebs-target-network-delay/README.md, openebs-pipeline/openebs-target-network-loss/README.md, openebs-pipeline/openebs-target-pod-failure/README.md
Signed-off-by: Udit Gaurav udit.gaurav@mayadata.io
- Update master to accommodate the result table
- fixes:
litmuschaos/litmus#1658
=> feat(result-table): Update master to accommodate the result table

tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, utils/result_update.py
- Add Readme table for the openebs test in master branch
- fixes:
https://github.com/litmuschaos/litmus/issues/1658
=> feat(table): Add Readme table for the openebs test in master branch

tests/container-kill_test.go, tests/disk-fill_test.go, tests/kubelet-service-kill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, utils/result_update.py
- Add Readme table for the generic test in master branch
- fixes:
https://github.com/litmuschaos/litmus/issues/1658
=> feat(table): Add Readme table for the generic test in master branch

.gitlab-ci.yml, Makefile, build/gitlab/stages/1-gke-setup/cluster-setup, build/gitlab/stages/2-gke-cleanup/cluster-cleanup, build/gitlab/stages/3-cluster-connect/cluster-connect, build/gitlab/stages/4-cluster-disconnect/cluster-disconnect, build/gitlab/stages/create-gke-cluster.yml, build/gitlab/stages/delete-gke-cluster.yml, build/gitlab/stages/vars.yml
- Add different build script for cluster creation and connection
- Setup e2e for litmus-portal and add a sample test
=> feat(litmus-portal): Setup e2e for litmus-portal and add a sample test

.gitlab-ci.yml, Makefile, pkg/utils/update.go, pkg/utils/watchJob.go, tests/pipeline-update_test.go, types/types.go, utils/pipeline_status_update.py
Issue:
fixes: https://github.com/litmuschaos/litmus/issues/1701
This PR is for the addition of Reamde.md for pipeline status check
=> feat(pipline status): Add readme for pipeline status check

README.md, generic-pipeline/README.md, generic-pipeline/container-kill/README.md, generic-pipeline/disk-fill/README.md, generic-pipeline/kubelet-service-kill/README.md, generic-pipeline/node-cpu-hog/README.md, generic-pipeline/node-drain/README.md, generic-pipeline/node-memory-hog/README.md, generic-pipeline/pod-cpu-hog/README.md, generic-pipeline/pod-delete/README.md, generic-pipeline/pod-memory-hog/README.md, generic-pipeline/pod-network-corruption/README.md, generic-pipeline/pod-network-duplication/README.md, generic-pipeline/pod-network-latency/README.md, generic-pipeline/pod-network-loss/README.md, openebs-pipeline/README.md, openebs-pipeline/openebs-control-plane-chaos/README.md, openebs-pipeline/openebs-pool-container-failure/README.md, openebs-pipeline/openebs-pool-pod-failure/README.md, openebs-pipeline/openebs-target-container-failure/README.md, openebs-pipeline/openebs-target-network-delay/README.md, openebs-pipeline/openebs-target-network-loss/README.md, openebs-pipeline/openebs-target-pod-failure/README.md
This PR is for: 
- Updating the root README.md file
- Also updating the jobs readme and adding pipeline batch in the pipeline readme
=> update(README): Add Batch and update all the README.md files

.gitlab-ci.yml, .master-plan.yml, Makefile, metrics/e2e-metrics
-  Add Master plan YAML for getting the generic e2e pipeline test coverage.
Issue:
fixes: https://github.com/litmuschaos/litmus/issues/1460
=> feat(e2e): Add Master plan yaml for getting the generic e2e pipeline test coverage

Makefile
=> fix(generic): Minor fixes in Makefile

.gitlab-ci.yml, tests/container-kill_test.go, tests/disk-fill_test.go, tests/kubelet-service-kill_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go
- Updating go image for newly added go experiment
- Later the BDDs for both experiments(go and ansible) will be added explicitly. 
Other updates:
- Moving the pipeline status check before disconnecting the  cluster
- Fix pod-network-duplication pipeline status update
=> update(image): Updating go image for newly added go experiment

.gitlab-ci.yml, .master-plan.yml, Makefile, go.mod, go.sum, tests/node-taint_test.go
=> feat(node-taint): Adding node-taint experiment in e2e pipeline

tests/kubelet-service-kill_test.go
=> feat(kubelet-service-kill): Adding ability to pass nodeName explicitly in kubelet-service-kill

.gitignore, .gitlab-ci.yml, CypressE2E/cypress.json, CypressE2E/cypress/fixtures/example.json, CypressE2E/cypress/integration/Login/login.spec.js, CypressE2E/cypress/integration/Workflow/workflow.spec.js, CypressE2E/cypress/integration/route.spec.js, CypressE2E/cypress/plugins/index.js, CypressE2E/cypress/support/commands.js, CypressE2E/cypress/support/index.js, CypressE2E/package-lock.json, CypressE2E/package.json, build/gitlab/stages/3-cluster-connect/cluster-connect, build/gitlab/stages/4-cluster-disconnect/cluster-disconnect
**Commits:**
- d62f9453835c9d2334d507c269073e5c7e43a1a7
- 0254ee11eb7cfdb4995c29e938d20b2069701cba
- 2bedee4cc2460350747ef0430a3dcc56398fc3fe
=> [Cherry-pick to litmus-portal]: Contains cypress tests

.gitlab-ci.yml, .master-plan.yml, Makefile, metrics/e2e-metrics
This PR contains:
- Add master plan yaml for getting the coverage percentage of openebs pipeline
Issue:
- fixed: https://github.com/litmuschaos/litmus/issues/1460
**Note for reviewers:**
- Any Pending test case than can be added in master YAML?
=> feat(coverage): Add master plan yaml for getting the coverage percentage for openebs pipeline

.gitlab-ci.yml, Makefile, pkg/utils/update.go, pkg/utils/watchJob.go, tests/install-litmus_test.go, tests/openebs-control-plane-chaos_test.go, tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go, tests/pipeline-status-update_test.go, utils/pipeline_status_update.py
This PR contains: 
- Modify both jobs updation and pipeline updation 
- Add one new job to update pipeline
=> feat(table): Add Readme table updation for the openebs test in GitHub page

README.md, generic-pipeline/generic.md, openebs-pipeline/openebs.md
- Update readme to take a new table with coverage
=> update(readme): Update readme to take a new table with coverage

Makefile
- Minor fix in admin mode test
=> fix(operator): Minor fix in admin mode test

types/types.go
- update litmus installation version with the new link in openebs
=> update(version): update litmus installation version with the new link in openebs tests

types/types.go
- Updating litmus installation version with the new link
=> update(version): update litmus installation version with new link

.master-plan.yml
- Adding some more test cases in master-plan.yml. The test cases include:
- Ansible experiments
- New component negative tests (involves an engine, experiment, and RBAC test).
=> feat(master-plan): Update master yaml with some new test cases

.gitlab-ci.yml, .master-plan.yml, Makefile, tests/node-io-stress_test.go, tests/pod-autoscaler_test.go, tests/pod-io-stress_test.go
- This PR is for adding e2e test for the newly added experiments. This includes:
- pod-io-stress
- node-io-stess
- pod- autoscaler
- The issue in updating the jobid in readme table
=> (newExp)chore: Add e2e test for new experiments

CONTRIBUTING.md
=> chore(Testing): Add contribution guide for Litmus E2E Testing

generic-pipeline/node-io-stress/README.md, generic-pipeline/pod-io-stress/README.md
=> update(new_test): Add readme for pod IO stress

.gitlab-ci.yml, CypressE2E/cypress.json, CypressE2E/cypress.prod.json, CypressE2E/cypress/integration/Parallel_Tests/Account_Settings/Account_Settings.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseSchedule.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseTemplates.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseWorkflow.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Create_Workflow/workflow.spec.js, CypressE2E/cypress/support/commands.js, CypressE2E/package.json, Makefile, README.md, build/gitlab/stages/3-cluster-connect/cluster-connect, k8s_scripts/LitmusInstall.sh, k8s_scripts/LitmusUninstall.sh
**This PR will** 
**- Add Config files for local setup and pipeline.**
**- Update the routes according to env.**
**- Update the Readme.md for litmus-portal-e2e.**
=> Added config for Local and pipeline setup and updated Readme.md

README.md, index.md
This PR will update details for Litmus-portal E2E pipeline in Readme.md for github and index.md for github pages.
=> Updated the Readme.md and Index.md with litmus-portal E2E details.

pkg/watch.go
=> fix(status): Minor fix in status check

generic-pipeline/pod-autoscaler/README.md
=> chore(docs): Add READM.md file for pod autoscaler experiment

CypressE2E/cypress/fixtures/Users.json, CypressE2E/cypress/integration/Basic_Setup/2. WelcomeModal/WelomeModal.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Account_Settings/Account_Settings.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Account_Settings/teaming.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Account_Settings/userManagement.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseSchedule.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseTemplates.spec.js, CypressE2E/cypress/integration/Parallel_Tests/BrowseWorkflow/browseWorkflow.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Community/community.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Create_Workflow/workflow.spec.js, CypressE2E/cypress/integration/Parallel_Tests/Routes/route.spec.js, CypressE2E/cypress/support/commands.js, CypressE2E/package-lock.json
**This PR will:**
**- Add more tests for User-management and Teaming section.**
**- Refactor some tests.**
Pipeline Test: https://gitlab.com/Jonsy13/litmus-e2e/-/pipelines/203406904
=> Added more tests for teaming-section and User management-section.

tests/container-kill_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-io-stress_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
- Adding an abort test for all supported experiments.
=> chore(abort): Add abort test for all supported experiments

pkg/install.go
=> chore(update): Update new ENV variables in E2E

.gitlab-ci.yml
=> chore(e2e): Trigger jobs according to the ENV set

metrics/e2e-metrics, pkg/update.go, templates/.component-test-template.yml, templates/.node-level-test-template.yml, templates/.pod-level-test-template.yml, tests/pipeline-update_test.go, utils/pipeline_status_update.py
=> chore(script): Add python script to update pipeline details

templates/.node-level-test-template.yml
=> fix(syntax): Fix syntax for node-level test

engine/job-cleanup-policy_test.go, pkg/environment/environment.go, pkg/install.go, pkg/types/types.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/node-cpu-hog_test.go, tests/node-io-stress_test.go, tests/node-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, tests/without-appinfo_test.go
=> chore(lib_Image): Add ci lib images for e2e test

engine/annotation-check_test.go, nginx/nginx.yml, pkg/cleanup.go, pkg/update.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-io-stress_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go
=> chore(bdd): Add test for running experiment when annotation check is true

pkg/environment/environment.go, pkg/install.go, pkg/types/types.go, templates/.pod-level-test-template.yml, tests/litmus-cleanup_test.go
Signed-off-by: udit <udit.gaurav@mayadata.io>
=> Fix: Update ENVs and kill commands

.master-plan.yml, Makefile, pkg/environment/environment.go, pkg/install.go, pkg/types/types.go, templates/.component-test-template.yml, templates/.node-level-test-template.yml, templates/.pod-level-test-template.yml, tests/ec2-terminate_test.go
Signed-off-by: udit <udit.gaurav@mayadata.io>
=> Chore(tests): Add test for ec2-terminate experiment and some refactoring

README.md, master-plan.md
Signed-off-by: udit <udit.gaurav@mayadata.io>
This PR adds:
- master-plan.md to add the details for updating the `.master-plan.yml`.
- Update README
=> chore(readme): Add readme for udpating mater-plan.yml

.gitlab-ci.yml, .master-plan.yml, Makefile, k8s_scripts/LitmusInstall.sh, master-plan.md, metrics/e2e-metrics
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**This PR will add master-plan.yml and e2e-metrics script for litmus-portal.**
Sample Gitlab-pipeline run can be seen here - https://gitlab.com/Jonsy13/litmus-e2e/-/pipelines/238235479
=> chore (Litmus-portal) : Added master-plan.yml and e2e-metrics script.

build/gitlab/stages/3-cluster-connect/cluster-connect
**This PR will add a minor change in branch name.**
=> Added Minor Branch Change.

_layouts/template.html, portal-pipeline/pipeline-runs/portal-ga.html, portal-pipeline/pipeline-runs/portal-rc.html, portal-pipeline/pipeline-runs/portal-run.html, portal-pipeline/portal.md
**This PR will add Initial HTML files for Litmus-Portal pipelines updates.**
**Can be previewed here -**  https://jonsy13.github.io/test-litmus-e2e/
=> Added Initial HTML files for Litmus-Portal pipeline updates.

utils/pipeline_status_update.py
Signed-off-by: Oum Kale <oumkale@chaosnative.com>
For Demo : [Link](https://oumkale.github.io/litmus-e2e/generic-pipeline/pipeline-runs/pod-level-run.html)
This PR will add bar graph for total coverage.
On every experiment it will get modified.
=> chore(tests) : Added coverage for tests

pkg/install.go
Signed-off-by: uditgaurav <udit@chaosnative.com>
- Fix the current broken pipeline due to the removal of annotationCheck from default engine spec.
=> Chore(Fix): Fix pipeline for annotation check field

.github/workflows/node-level-pipeline.yml, .github/workflows/scheduled-node-level-pipeline.yml
Signed-off-by: uditgaurav <udit@chaosnative.com>
- Add node level pipeline for scheduled runs and on-demand runs as well.
- This includes all node level  (infra experiment) tests.
- This pipeline is the conversion of this https://github.com/litmuschaos/litmus-e2e/blob/generic/templates/.node-level-test-template.yml GitLab pipeline in GitHub actions.
=> Chore(node-level): Add node level pipeline

pkg/environment/environment.go, pkg/install.go, pkg/types/types.go
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
=> chore(lib-image): adding lib-image env

pkg/environment/environment.go, pkg/get.go, pkg/install.go, pkg/types/types.go, pkg/watch.go
Signed-off-by: uditgaurav <udit@chaosnative.com>
- Add helper pod logs in the e2e tests that help in getting the exact reason for helper failure.
- Add lib image fix in the master branch.
=> Chore(helper): Print helper pod logs as well for debugging purpose in the e2e tests

.github/workflows/pod-level-pipeline.yml, tests/env-from-secret-and-cm_test.go
Signed-off-by: udit <udit@chaosnative.com>
- Speed up pod level pipeline by running parallel tests.
=> Chore(speedup_pipeline): Fix pod level pipeline to run parallel tests and speedup the total pipeline duration

.github/workflows/pod-level-pipeline.yml, pkg/create.go
Signed-off-by: udit <udit@chaosnative.com>
=> Chore(annotate): Add annotation to the Application Under Chaos

Cypress/cypress/integration/Parallel_Tests/MyHub/crudMyHub.spec.js
This PR adds e2e for :
- MyHub CRUD operations
=> Added e2e tests for MyHub

components/result/run-history_test.go, pkg/environment/environment.go, pkg/install.go, pkg/types/types.go
Signed-off-by: Oum Kale <oumkale@chaosnative.com>
Fixing update resource and adding node level variables for chaos experiment
=> Fixing update resource and adding node level variables

Cypress/Readme.md
=> Added Minor link fixes in Readme.md

portal-pipeline/portal.md
=> Fixed the broken links

Cypress/Readme.md
=> Fix link to github actions workflow in Cypress Readme

components/operator/admin-mode_test.go, pkg/create.go, pkg/get.go, tests/kubelet-service-kill_test.go, tests/node-drain_test.go, tests/node-taint_test.go, tests/with-appinfo_test.go
Signed-off-by: Vaibhav Vishal <vaibhavvishal40@gmail.com>
- This PR contains the refactored test code for some common functions.
=> Refactor Go tests for some common functions

pkg/cleanup.go, pkg/environment/environment.go, pkg/install.go, pkg/types/types.go
Signed-off-by: Oum Kale <oumkale@chaosnative.com>
Adding args and command envs.
=> chore(update): Adding args and command envs 

Cypress/cypress.ns-scope.json, Cypress/cypress.prod.json
Add cypress-react-selector to env for production and ns-scope.
=> Add cypress-react-selector to env of cypress.prod.json & cypress.ns-scope.json

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Workflow_Stats/workflowStats.spec.js, Cypress/cypress/pages/workflow.js
[2f08974](https://github.com/litmuschaos/litmus-e2e/pull/330/commits/2f08974b5dab4ff3edf6bdc7a92e1672a355faff) Added validation of workflow stats for custom chaos workflow schedule for both positive and negative cases (Test Case 2 & 3)
[19a6b9f](https://github.com/litmuschaos/litmus-e2e/pull/330/commits/19a6b9f2082d280047e8d3cbb578032bca134f33) Added test for checking the accessibility of workflow statistics tab (Test Case 1)
=> Tests for Workflow Statistics

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/pages/workflow.js
Add validation of statistics for recurring workflow:-
Test 4 of [issue 316 ](https://github.com/litmuschaos/litmus-e2e/issues/316):-
(Test case to schedule a Custom Chaos workflow (Recurring) & verify the workflow statistics data [positive case --> Existing target App])
Test 5 of [issue 316 ](https://github.com/litmuschaos/litmus-e2e/issues/316):-
(Rerun a non-recurring workflow & verify the statistics.)
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
=> Add validation of stats for recurring workflow

Cypress/cypress/integration/Basic_Setup/1. Login/login.spec.js, Cypress/cypress/integration/Basic_Setup/2. GetStarted/GetStarted.spec.js, Cypress/cypress/integration/Parallel_Tests/Account_Settings/1. Account_Settings.spec.js, Cypress/cypress/integration/Parallel_Tests/Account_Settings/2. teaming.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Routes/route.spec.js, Cypress/cypress/integration/smoke/smoke.js, Cypress/cypress/kube-apis/apis.js, Cypress/cypress/pages/login.js, Cypress/cypress/pages/workflow.js, Cypress/cypress/support/index.js
Add validation of existence of workflow on cluster
**Issue**
=> Resource validation on cluster

Cypress/cypress/fixtures/sample-workflow.yaml, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js
Change upload workflow manifest, Replace predefined schedule with upload workflow schedule in predefined worfklow and template workflow, fix predefined workflow failure
**Issue**
=> Change upload workflow manifest, Fix predefined workflow failure

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/disableWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/kube-apis/apis.js, Cypress/cypress/pages/workflow/workflowClusterValidation.js, Cypress/cypress/pages/workflow/workflowOperations.js, Cypress/cypress/pages/workflow/workflowValidation.js
- Add test to check the existence of cron workflow
- Add test to disable the recurring schedule
- Refactor check browsing table and validate verdict
- Add test to validate experiment table
**Issue**
=> Optimize and refactor browsing table, verdict validation, disable recurring schedule, cron workflow existence

Cypress/cypress.json, Cypress/cypress/integration/Parallel_Tests/Data_Source/addDataSource.spec.js
Add test for data source creation, configuration, and deletion
**Issue**
- Needed https://github.com/litmuschaos/litmus/pull/3364
=> Add test for data source creation, configuration, and deletion

.github/workflows/nightly-portal-pipeline.yml, .github/workflows/portal-pipeline.yml
=> Fixed datasource endpoint in chaoscenter pipeline

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/disableWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/pages/workflow/workflowGraphStats.js, Cypress/cypress/pages/workflow/workflowValidation.js, Cypress/cypress/support/pages.js
Add validation for workflow statistics graph (Experiment radial chart, Resilience score chart & Pass-Fail bar)
**Issue**
- Needed https://github.com/litmuschaos/litmus/pull/3365
=> Add validation for workflow statistics graph

.github/workflows/nightly-vmware-experiment-pipeline.yml, .github/workflows/vmware-experiment-pipeline.yml, Makefile, pkg/environment/environment.go, pkg/install.go, pkg/types/types.go, platform/vmware/vm-poweroff_test.go
VMWare E2E Experiment Pipeline automates the E2E BDD tests for LitmusChaos VMWare experiments such as the VMWare VM-Poweroff experiment.
**Issue**
=> VMWare E2E Experiment Pipeline

.github/workflows/nightly-component-pipeline.yml, .github/workflows/nightly-node-level-pipeline.yml, .github/workflows/nightly-pod-level-pipeline.yml, .github/workflows/pod-level-pipeline.yml, pkg/status.go
=> Fixes backend pipelines for litmus 2.4.0 

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/workflowCRUDOps.spec.js, Cypress/cypress/integration/Parallel_Tests/Data_Source/addDataSource.spec.js, Cypress/cypress/pages/workflow/workflowCustom.js
- Fix failures due to show experiment modal
- Add test for revert-chaos within custom workflow
- Add validation for both bars at rerun workflow
- Add test for Datasource for changing the name and validating Datasource table after Datasource deletion.
**Issue**
- Required https://github.com/litmuschaos/litmus/pull/3398
=> Fix failures due to show experiment modal, Add validation for both bars at rerun workflow, Add test for Datasource

Cypress/cypress/integration/Parallel_Tests/Dashboard/createDashboard.js, Cypress/cypress/pages/dashboard/dashboardConfiguration.js, Cypress/cypress/support/pages.js
Add test for dashboard creation, configuration, and deletion
**Issue**
Required updates from https://github.com/litmuschaos/litmus/pull/3406
=> Add test for dashboard creation, configuration, deletion

Cypress/Readme.md
Update readme with instructions to get K8s API server url and token
**Issue**
=> Update readme with instructions to get K8s API server url and token

src/components/Header/index.jsx
The GitHub icon on the header was earlier directing to the LitmusChaos slack instead of the litmus-e2e GitHub repo.
=> fix GitHub URL

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/customWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/preDefinedWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/recurringWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/uploadWorkflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Create_Workflow/workflowCRUDOps.spec.js
**This PR will fix the failing tests due to some recent changes.**
**Issue**
=> (Chaos-Center): Fixed the failing tests

Cypress/cypress/fixtures/graphql/mutation.js, Cypress/cypress/fixtures/graphql/queries.js, Cypress/cypress/integration/Api_Tests/authentication/user.spec.js, Cypress/cypress/integration/Api_Tests/graphql/cluster.spec.js, Cypress/cypress/integration/Api_Tests/graphql/myhub.spec.js, Cypress/cypress/integration/Api_Tests/graphql/workflow.spec.js, Cypress/cypress/plugins/index.js, Cypress/cypress/support/commands.js, Cypress/package-lock.json, Cypress/package.json
- Updated the graphql and authentication tests to clear the MongoDB database before running tests.
- Creates a new agent before each test run and wait for it to become active.
- Added tests for chaos workflow related APIs
- Added the test findings at #362 
**Issue**
=> added chaos workflow related tests

.github/workflows/m-agent-experiment-pipeline.yml, .github/workflows/nightly-m-agent-experiment-pipeline.yaml
Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>
- Mandates the Delete_VM step regardless of the outcome of the preceding steps
- Removes undefined ENVs from pipeline workflow
- Hardcodes `litmuschaos/litmus-go:m-agent` image as an ENV input to the experiment in nightly pipeline
fixes #375
**Issue**
=> m-agent Pipeline Fix

.github/workflows/gcp-experiment-pipeline.yml, .github/workflows/m-agent-experiment-pipeline.yml, .github/workflows/nightly-gcp-experiment-pipeline.yml, .github/workflows/nightly-m-agent-experiment-pipeline.yaml
Adds GCP auth@v0 Github Action for gcloud sdk setup in:
- GCP Experiment Pipeline
- Nightly GCP Experiment Pipeline
- m-agent Experiment Pipeline
- Nightly m-agent Experiment Pipeline
fixes #382
**Issue**
Demo workflow runs:
- https://github.com/neelanjan00/litmus-e2e/actions/runs/2349924830
- ~~https://github.com/neelanjan00/litmus-e2e/actions/runs/2349930936~~ https://github.com/neelanjan00/litmus-e2e/actions/runs/2361763363
=> Add gcloud Auth Github Action

Cypress/cypress/integration/Parallel_Tests/Account_Settings/2. teaming.spec.js, litmus/litmusctl_tests.sh, litmus/utils.sh
Signed-off-by: Vedant Shrotria <vedant.shrotria@harness.io>
**Issue**
=> Fixed litmusctl tests & flaky test in authentication

Cypress/cypress.json, Cypress/cypress.ns-scope.json, Cypress/cypress.prod.json, Cypress/cypress/fixtures/gitopsInput.json, Cypress/cypress/fixtures/graphql/mutations/gitOps.js, Cypress/cypress/fixtures/graphql/mutations/imageRegistry.js, Cypress/cypress/fixtures/graphql/queries/imageRegistry.js, Cypress/cypress/fixtures/imageRegistryInput.json, Cypress/cypress/integration/Api_Tests/authentication/project.spec.js, Cypress/cypress/integration/Api_Tests/graphql/gitops.spec.js, Cypress/cypress/integration/Api_Tests/graphql/imageRegistry.spec.js, Cypress/cypress/integration/Api_Tests/graphql/myhub.spec.js, Cypress/cypress/plugins/index.js, Cypress/cypress/support/commands.js
- Added Gitops 
- Added ImageRegistry tests
- Fixed errors in project api tests
**Note:** Update Gitops test is failing with error message `Failed to setup Gitops : mkdir /tmp/gitops_test: read-only file system`
=> Added Gitops and ImageRegistry tests

Cypress/ApiTesting.md, Cypress/Readme.md, Cypress/cypress/integration/Api_Tests/authentication/project.spec.js, Cypress/cypress/integration/Api_Tests/graphql/cluster.spec.js, Cypress/cypress/integration/Api_Tests/graphql/gitops.spec.js, Cypress/cypress/integration/Api_Tests/graphql/imageRegistry.spec.js, Cypress/cypress/integration/Api_Tests/graphql/myhub.spec.js, Cypress/cypress/integration/Api_Tests/graphql/workflow.spec.js, Cypress/cypress/support/commands.js
- Added API Testing Documentation
- Updated `cluster-k8s-manifest.yml` link in README.md
- Completely removed browser interaction with litmus portal for API Testing
- Created `initialRBACSetup` function
- 
=> add initialRBACSetup, remove lismusctl use for api testing and add api testing doc
