litmuschaos/litmus-e2e

tests/openebs-target-pod-failure_test.go
issue - https://github.com/litmuschaos/litmus/issues/1199
**_This PR contains_**
- This PR contains the addition of validations (Test cases) for openebs target pod failure
**_The tests added are:_**
- **Verdict Check**
- It involves a basis verdict check of the experiment. It is already done at the end of the experiment.
- **Resource Version test**
- In the resource version test, it has been tested whether the resource version of the target pod has been changed after chaos injection. For successful chaos injection - the value of Resource Version should change.
- **Container Restart Count test**
- In the container restart count test, we are testing whether the number of container restart count is getting changed or not after chaos …
=> (feat): Adding Validations (Test cases) for openebs target pod failure

tests/openebs-target-container-failure_test.go
issue - https://github.com/litmuschaos/litmus/issues/1198
**_This PR includes_**
-  Adding Validations (Test cases) for openebs target container failure
**_Test cases which have been added_**
- **Verdict Check**
- It involves a basis verdict check of the experiment. It is already done at the end of the experiment.
- **Resource Version test**
- In the resource version test, it has been tested whether the resource version of the target pod has been changed after chaos injection. For successful chaos injection - the value of Resource Version should change.
- **Container Restart Count test**
- In the container restart count test, we are testing whether the number of container restart count is getting changed or not after chaos injection. For …
=> (feat): Adding Validations (Test cases) for openebs target container failure

tests/openebs-pool-container-failure_test.go
issue- https://github.com/litmuschaos/litmus/issues/1196
**_This PR contains_**
- The addition of Validations (Test cases) in openebs pool container failure experiment.
**_Test cases which have been added_**
- **Verdict Check**
- It involves a basis verdict check of the experiment. It is already done at the end of the experiment.
- **Resource Version test**
- In the resource version test, it has been tested whether the resource version of the CSP pod has been changed after chaos injection. For successful chaos injection - the value of Resource Version should change.
- **Container Restart Count test**
- In the container restart count test, we are testing whether the number of container restart count is getting changed or not after chaos …
=> (feat): Adding Validations (Test cases) for openebs-pool-container-failure experiment

utils/chaosengine.j2
- Adding EngineState in the ChaosEngine spec
=> Adding EngineState in the ChaosEngine spec

tests/openebs-pool-container-failure_test.go, tests/openebs-pool-pod-failure_test.go, tests/openebs-target-container-failure_test.go, tests/openebs-target-network-delay_test.go, tests/openebs-target-network-loss_test.go, tests/openebs-target-pod-failure_test.go
**_This PR is for:_**
- Fixing the chaosengine and chaosrunner A/C to the latest changes
- The latest changes mentioned above is 
- Automatically deletion of runner pod once it gets completes
- Removing status from subresources
=> (Enhancement): Changing the chaosengine and chaosrunner A/C to the latest changes

tests/container-kill_test.go, tests/disk-fill_test.go, tests/install-litmus_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, types/types.go
- Using custom Images of different components of litmus for running pipelines
- Currently, we are only taking the image tag from the Gitlab ENV. This Issue is for getting the complete image of different components which are chaos operator, chaos runner , chaos experiment form the ENV or custom values.
- For taking custom image values Gitlab will have following ENVs:
1. REPO_NAME: litmuschaos (default)
2. OPERATOR_IMAGE: chaos-operator (default)
3. RUNNER_IMAGE: chaos-runner (default)
4. EXPERIMENT_IMAGE: ansible-runner (default)
5. IMAGE_TAG: ci (default)
=> (feat): Using custom Images of different components of litmus for running pipelines

tests/node-drain_test.go
- Modify node name field in chaos engine of node drain
=> (fix): Modify node name field in chaos engine of node drain

Makefile, build/gitlab/stages/3-cluster-connect/cluster-connect, build/gitlab/stages/4-cluster-disconnect/cluster-disconnect, tests/pod-network-corruption_test.go, tests/pod-network-latency_test.go
- This PR contains:
- A different target cluster for generic and openebs experiments which will help in parallel execution of both the pipelines. For this, a different `IP` , `user` , `password` is required which are `litmus_ip` , `litmus_user` & `litmus_pass` for generic pipelines and these are placed in GitLab ENVs.
- Updated the engine changes from chaos-charts to edit the engine name.
=> chore(cluster): Separating target cluster for generic and openebs pipelines and some fixes

.gitlab-ci.yml, Makefile, tests/container-kill_test.go, tests/disk-fill_test.go, tests/kubelet-service-kill_test.go, tests/node-cpu-hog_test.go, tests/node-memory-hog_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, types/types.go
- Add pod memory hog experiment in the litmus-e2e pipeline 
- Add Go-based experiment image in few experiments like in pod-memory hog, pod-cpu-hog, pod-delete. 
fixes:
- https://github.com/litmuschaos/litmus/issues/1652
=> chore(BDD): Add pod network duplication also go experiment Image in e2e pipeline 

metrics/e2e-metrics, pkg/utils/update.go, tests/pipeline-update_test.go, utils/pipeline_status_update.py, vendor/github.com/onsi/gomega/go.mod, vendor/modules.txt
-  Add coverage percentage bar in readme and ci website
**Issue:**
- fixes: https://github.com/litmuschaos/litmus/issues/1748
**How are we updating the coverage percentage in Readme table:**
- We will get the coverage percentage from`e2e-metrics` job, then we will save it in some file called `coverage.txt` then in the `pipeline status update` job we will use this file to get the coverage value and add it in the readme file with a new column.
- Clicking on the coverage value will take us to the `.master-plan.yml` which is used to calculate the coverage.
=> feat(coverage): Add coverage percentage bar in readme and ci website for generic

metrics/e2e-metrics, pkg/utils/update.go, tests/pipeline-status-update_test.go, utils/pipeline_status_update.py
- Add coverage percentage in the readme for openebs
**Issue:**
- fixes: litmuschaos/litmus#1748
**How are we updating the coverage percentage in Readme table:**
- We will get the coverage percentage from`e2e-metrics` job, then we will save it in some file called `coverage.txt` then in the `pipeline status update` job we will use this file to get the coverage value and add it in the readme file with a new column.
- Clicking on the coverage value will take us to the `.master-plan.yml` which is used to calculate the coverage.
=> feat(coverage): Add coverage percentage in readme for openebs

.gitlab-ci.yml, CypressE2E/package.json
Added a smaller docker image Cypress/base:10 in place of Cypress/browsers as Cypress/browsers image was occupying large space on the runner. Now the size of Cypress/base is around 400 MB.
The Version is still upgraded one i.e. 4.11.0.
=> Added a Smaller docker Image for Cypress.

ansible/ansible-kubelet-service-kill_test.go, ansible/ansible-node-drain_test.go, pkg/environment/environment.go, pkg/get.go, pkg/install.go, pkg/types/types.go, tests/kubelet-service-kill_test.go, tests/node-drain_test.go, tests/node-taint_test.go
**What does this PR do/why do we need it?**
- Add Node Selector values for infra engine
This is due to spec changes in chaosengine:
```yaml
spec:
components:
nodeSelector: 
kubernetes.io/hostname: 'node02'   
```
=> feat(experiment): Add Node Selector values for infra engine

build/runner/Dockerfile
**What this PR does / why we need it?**
- As litmus portal pipeline has a docker runner/executor. This PR contains the Dockerfile of the image used as the default runner in the litmus portal pipeline.
=> chore(image): Add Dockerfile of the image used as default runner image

README.md, generic-pipeline/admin-mode/README.md, generic-pipeline/annotation-check/README.md, generic-pipeline/appinfo/README.md, generic-pipeline/engine-state/README.md, generic-pipeline/experiment-404/README.md, generic-pipeline/experiment-image/README.md, generic-pipeline/generic.md, generic-pipeline/job-cleanup-policy/README.md, generic-pipeline/reconcile-resiliency/README.md, generic-pipeline/service-account/README.md
Issue:
- resolved: - https://github.com/litmuschaos/litmus/issues/1923
**_This PR includes:_**
- Readme (docs) for new engine and experiment spec test.
- Updating the Readme for operator tests.
- Updating the [web site](https://litmuschaos.github.io/litmus-e2e) with new tests.
=> chore(new_test): Add Readme and result table in website for new tests

.gitlab-ci.yml
**This PR will remove reports:dotenv from gitlab-ci.yml (not required anymore).**
Pipeline Test: https://gitlab.com/Jonsy13/litmus-e2e/-/pipelines/201993788
=> (Minor-Change):Removed dotenv from gitlab-ci.yml.

utils/heatmap-coverage.py
This script creates heatmap matrix image for e2e website. The script is executed by:
```bash
python3 utils/heatmap-coverage.py pod-delete
```
Which checks for a CSV file named  ExperimentName.csv and creates a heatmap out of it. 
Sample run:
```
udit@ubuntu ~/g/s/g/l/litmus-e2e> python3 utils/heatmap-coverage.py pod-delete
Is the test added?
Validation                                               1.0
For deployment application                               1.0
For statefulset application                              0.0
For deployment config application                        0.0
PodsAffectedPercentage is 0                              1.0
PodsAffectedPercentage is 100                            0.0
PodsAffectedPercentage 0-100 …
```
=> chore(add): Add script to create coverage heatmap of an experiment

pkg/environment/clienset.go, pkg/file.go, pkg/install.go
- Set `imagePullPolicy` of chaos-runner to `Always` for testing in e2e.
The ChaosEngine spec after runner the edit function will look like:
```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
name: go-engine9
namespace: litmus
spec:
appinfo:
appns: litmus
applabel: run=nginx
appkind: 'deployment'
annotationCheck: 'false'
engineState: 'active'
#ex. values: ns1:name=percona,ns2:run=nginx
auxiliaryAppInfo: ''
chaosServiceAccount: pod-delete-sa
monitoring: false
jobCleanUpPolicy: 'retain'
components:
runner:
imagePullPolicy: Always
experiments:
- name: pod-delete
```
=> chore(imagePullPolicy): Add image pull policy to Always in engine for testing latest runner

.master-plan.yml, Makefile, manifest/without_appinfo/kubelet-service-kill.yml, manifest/without_appinfo/node-cpu-hog.yml, manifest/without_appinfo/node-drain.yml, manifest/without_appinfo/node-io-stress.yml, manifest/without_appinfo/node-memory-hog.yml, manifest/without_appinfo/node-taint.yml, manifest/without_appinfo/pod-autoscaler.yml, pkg/ansible-install.go, pkg/environment/clienset.go, pkg/install.go, templates/.component-test-template.yml, templates/.node-level-test-template.yml, templates/.pod-level-test-template.yml, tests/app-cleanup_test.go, tests/litmus-cleanup_test.go, tests/without-appinfo_test.go
- This PR includes Without appinfo test for node-level experiments and some refactoring and restructuring stuff.
Issue:
- https://github.com/litmuschaos/litmus/issues/1532
=> chore(new_test): Add without appinfo test for Node level experiment and some refactoring

engine/job-cleanup-policy_test.go, pkg/environment/environment.go, pkg/file.go, pkg/get.go, pkg/install.go, pkg/types/types.go, pkg/validate.go, tests/container-kill_test.go, tests/disk-fill_test.go, tests/kubelet-service-kill_test.go, tests/litmus-cleanup_test.go, tests/node-cpu-hog_test.go, tests/node-drain_test.go, tests/node-io-stress_test.go, tests/node-memory-hog_test.go, tests/node-taint_test.go, tests/pipeline-update_test.go, tests/pod-autoscaler_test.go, tests/pod-cpu-hog_test.go, tests/pod-delete_test.go, tests/pod-io-stress_test.go, tests/pod-memory-hog_test.go, tests/pod-network-corruption_test.go, tests/pod-network-duplication_test.go, tests/pod-network-latency_test.go, tests/pod-network-loss_test.go, utils/pipeline_status_update.py
Signed-off-by: udit <udit.gaurav@mayadata.io>
Component level failures:
====================
Invalid app info test:  The ChaosEgine verdict is not patched to Fail for invalid appinfo: The reason could be the time taken to update the Engine verdict.
**[SOLVED]:** _Solved by adding a retry on Verdict check for both ChaosEngine and ChaosResult. Now it will check the verdict for 30sec._
Abort test: It is also Failed for the same reason the verdict is not pathed in the given time. The experiment used is pod cpu hog.
**[TEMPRORY SOLVED]:** _The Chaos Result Verdict is not patching to stopped. This could be due to the limited time available after abort which is used in killing the process and no time left to update the ChaosResult. Used a different experiment(pod-delete) that does not have any …
=> chore(Fix): Fix the current pipeline failures

pkg/status.go
It is not recommended to use `len` for the empty string test. It is not considered more idiomatic in Go.
=> fix: Improved empty string

Cypress/cypress/integration/Parallel_Tests/Create_Workflow/template.spec.js
The test for saving the workflow often fails when the cypress server looks for eq(1). 
Don't think it is needed. The test runs fine without it.
=> eq(1) selector is not needed

.github/workflows/pod-level-pipeline.yml, .github/workflows/scheduled-pod-level-pipeline.yml, build/debug.sh
Signed-off-by: udit <udit@chaosnative.com>
- Shift pod level pipeline clusters from kubeadm on ec2 to a transient kind/k3s cluster
- We can use a shared runner also in place of the self-hosted runner.
- The pipeline has a well-defined debug step to catch any test failure.
- https://github.com/litmuschaos/litmus-e2e/issues/299
=> [Migrate]: Pod level pipeline from self hosted runner to shared runner

.github/workflows/portal-pipeline.yml, .github/workflows/scheduled-Portal-pipeline.yml
- Corrected name from `Scheuled` to `Scheduled`
- Fixed pipeline name to follow a single convention (`-` as a separator). It will be helpful to dynamically filter scheduled pipelines from all pipelines in the e2e dashboard.
=> fix(pipeline): follow a single convention for pipeline naming

public/locales/en/translation.yaml, src/api/sendRequest.js, src/components/CustomAccordion/index.jsx, src/components/CustomAccordion/styles.js, src/components/CustomRadialProgressChart/styles.js, src/components/Table/TimelineComponent.jsx, src/components/Table/VerticalTabs.jsx, src/components/Table/index.jsx, src/components/Table/styles.js, src/constants/endpoints.js, src/containers/app/App.jsx, src/pages/AllWorkflows/index.jsx, src/pages/WorkflowPage/index.jsx
This PR adds fetch logs functionality in e2e dashboard UI. 
Closes litmuschaos/litmus#3112
This PR contains commit of #333 and adds fetch log functionality on top of that.
=> add fetch logs functionality in e2e dashboard UI

pkg/environment/environment.go, tests/container-kill_test.go
This PR fixes two failing tests in the Pod Level Pipeline:
1. Pod Network Latency tests in the where the `Duration` is now bumped up from 90 seconds to 180 seconds 
2. Container Kill tests where the test BDD for Pumba has been disabled
**Issue**
=> Pod Level Pipeline Fixes (Pod Network Latency Tests and Container Kill Tests)

Cypress/cypress/fixtures/errorCodes.js, Cypress/cypress/integration/Api_Tests/authentication/project.spec.js, Cypress/cypress/integration/Api_Tests/graphql/myhub.spec.js
The final PR for authentication api which contains tests for project related apis. The findings from this test are reported at #362 .
cc @Jonsy13
=> create auth api tests for project endpoints

Cypress/cypress/fixtures/endpoints.js, Cypress/cypress/fixtures/errorCodes.js, Cypress/cypress/fixtures/graphql/mutations/workflows.js, Cypress/cypress/integration/Api_Tests/authentication/project.spec.js, Cypress/cypress/integration/Api_Tests/authentication/user.spec.js, Cypress/cypress/integration/Api_Tests/graphql/cluster.spec.js, Cypress/cypress/integration/Api_Tests/graphql/gitops.spec.js, Cypress/cypress/integration/Api_Tests/graphql/imageRegistry.spec.js, Cypress/cypress/integration/Api_Tests/graphql/myhub.spec.js, Cypress/cypress/integration/Api_Tests/graphql/workflow.spec.js, Cypress/cypress/integration/Parallel_Tests/Account_Settings/2. teaming.spec.js, Cypress/cypress/integration/Parallel_Tests/Data_Source/addDataSource.spec.js, Cypress/cypress/integration/smoke/smoke.spec.js, Cypress/cypress/pages/login.js, Cypress/cypress/plugins/index.js, Cypress/cypress/support/commands.js
- Updated all test cases to take url from fixtures
- Uncomment all commented tests and added the report [here](https://github.com/litmuschaos/litmus-e2e/issues/362#issuecomment-1162638528)
- Divided setup function into multiple smaller reusable functions
- Reduced tests time by removing waiting period between each login.
- Added fallback to local mongodb if environment variable is not set
=> Updated project setup and uncommented all failing tests

.github/workflows/aws-experiment-pipeline.yml, .github/workflows/azure-experiment-pipeline.yml, .github/workflows/component-pipeline.yml, .github/workflows/gcp-experiment-pipeline.yml, .github/workflows/m-agent-experiment-pipeline.yml, .github/workflows/nightly-aws-experiment-pipeline.yml, .github/workflows/nightly-azure-experiment-pipeline.yml, .github/workflows/nightly-component-pipeline.yml, .github/workflows/nightly-gcp-experiment-pipeline.yml, .github/workflows/nightly-m-agent-experiment-pipeline.yaml, .github/workflows/nightly-pod-level-pipeline.yml, .github/workflows/nightly-vmware-experiment-pipeline.yml, .github/workflows/pod-level-pipeline.yml, .github/workflows/vmware-experiment-pipeline.yml
Signed-off-by: uditgaurav <udit@chaosnative.com>
**Issue**
=> Fix k3s build for running litmus-e2e

apps/nginx/nginx.yml, build/Dockerfile, components/operator/admin-mode_test.go, components/operator/reconcile-resiliency_test.go, pkg/common.go, pkg/environment/environment.go, pkg/install.go, pkg/status.go, pkg/types/types.go, pkg/watch.go, tests/disk-fill_test.go, tests/pod-affected-perc-ton-parallel_test.go, tests/pod-affected-perc-ton-series_test.go, tests/pod-memory-hog_test.go
**Issue**
- https://github.com/litmuschaos/litmus/issues/4605
=> Fix build pipeline and test cases for chaos-operator and litmus-go

.github/workflows/litmusctl-test-pipeline.yml, Cypress/cypress/fixtures/test.yaml, litmus/install-portal.sh, litmus/litmusctl_tests.sh, litmus/mongo-values.yml, litmus/utils.sh
=> Litmusctl End-to-End Tests
